= REST API - Account
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[resources-account]]
== Account

account 리소스는 Account를 만들거나 조회할 때 사용한다.

[[resources-account-list]]
=== Account 목록 조회

`GET` 요청을 사용하여 서비스의 모든 Account를 조회할 수 있다.

operation::get-account[snippets='response-fields,curl-request,http-response,links']

[[resources-account-create]]
=== Account 생성

`POST` 요청을 사용해서 새 Account를 만들 수 있다.

operation::create-account[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields,links']

[[resources-account-get]]
=== Account 조회

`Get` 요청을 사용해서 기존 Account 하나를 조회할 수 있다.

operation::get-account[snippets='request-fields,curl-request,http-response,links']

[[resources-account-update]]
=== Account 수정

`PUT` 요청을 사용해서 기존 Account를 수정할 수 있다.

operation::update-account[snippets='request-fields,curl-request,http-response,links']

[[resources-account-delete]]
=== Account 삭제

`DELETE` 요청을 사용해서 기존 Account를 삭제할 수 있다. - 회원탈퇴

operation::delete-account[snippets='request-fields,curl-request,http-response,links']