export const QUERY_NOTICE_REQUEST = "QUERY_NOTICE_REQUEST";
export const QUERY_NOTICE_SUCCESS = "QUERY_NOTICE_SUCCESS";
export const QUERY_NOTICE_FAILURE = "QUERY_NOTICE_FAILURE";


export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";

